
#ifndef __GLOBAL_H
#define __GLOBAL_H


#include<fstream.h>
#include<conio.h>
#include<stdio.h>
#include<process.h>
#include<string.h>
#include<ctype.h>
#include<dos.h>
#include<direct.h>
#include<stdlib.h>
#include<iomanip.h>


#define CTRL_C 0x03
#define CTRL_D 0x04
#define CTRL_R 0x12
#define DELETE 0x53
#define ENTER  0x0D
#define BCKSPC 0x08
#define ESC    0x1B
#define TAB    0x09
#define UP_ARROW    0x48
#define LEFT_ARROW  0x4B
#define RIGHT_ARROW 0x4D
#define DOWN_ARROW  0x50


#endif		/* __GLOBAL_H*/
